image: marcoturi/ionic:latest

stages:
  - test
  #- deploy

before_script:
  - yarn config set cache-folder .yarn
  - yarn
  - npm run post-install

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/
    - .yarn

build_web:
  stage: test
  #only:
  #    - master
  script:
    - npm run lint
    #- npm run scss-lint
    - npm run test
    - npm run build
    - npm run e2e

# build_ios:
#   stage: deploy
#   only:
#     - release
#   script:
#     - ./sh/ionic-login.sh
#     - ls
#     - npm run ios:release:ci
#     - ./sh/ionic-package-ios.sh

# build_android:
#   stage: deploy
#   only:
#     - release
#   script:
#     - ls
#     - npm run android:release
#     - ls ./platforms/android/build/outputs/apk/android*.apk
#   artifacts:
#     paths:
#       - platforms/android/build/outputs/apk/