image: beevelop/ionic:latest

stages:
  - test
  #- deploy

before_script:
  #- yarn config set cache-folder .yarn
  #- yarn
  #- npm run post-install
  - export MAVEN_USER_HOME=`pwd`/.maven
    - ./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-npm -DnodeVersion=v10.13.0 -DnpmVersion=6.4.1 -Dmaven.repo.local=$MAVEN_USER_HOME
    - ./mvnw com.github.eirslett:frontend-maven-plugin:npm -Dmaven.repo.local=$MAVEN_USER_HOME

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
  - .maven/
    #- node_modules/
    #- .yarn

build_web:
  stage: test
  #only:
  #    - master
  script:
    - npm run lint
    #- npm run scss-lint
    - npm run test:ci
    #- npm run test
    - npm run test:coverage
    - npm run build
    - npm run e2e

# build_ios:
#   stage: deploy
#   only:
#     - release
#   script:
#     - ./sh/ionic-login.sh
#     - ls
#     - npm run ios:release:ci
#     - ./sh/ionic-package-ios.sh

# build_android:
#   stage: deploy
#   only:
#     - release
#   script:
#     - ls
#     - npm run android:release
#     - ls ./platforms/android/build/outputs/apk/android*.apk
#   artifacts:
#     paths:
#       - platforms/android/build/outputs/apk/