image: beevelop/ionic:latest

stages:
  - test
  - deploy

before_script:
  - yarn config set cache-folder yarn-cache
  - yarn
  - gem install scss_lint
  - npm run post-install

cache:
  paths:
    - yarn-cache/

build_web:
  stage: test
  script:
    - npm run lint
    - npm run scss-lint
    - npm run test
    - npm run build
    - npm run e2e