os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.13.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g ionic
install:
  - npm ci && npm run build
script:
  - npm run test:ci
  - npm run build --prod
  - npm run e2e
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false